### ISSUE TITLE
bug: incorrect hours on dashboard for midnight shifts

### ISSUE THREAD

**Issue by QiLinXue** [volunteeringpeel/volunteeringpeel#111]
Steps to reproduce:
- Create shift that goes to midnight (12:00 AM)
- Sign up for the shift
- Go to dashboard and the #of hours will be an extra 12.

**Comment by RetroCraft** [comment]
Turns out this was caused by user error.

Will create a patch to prevent this from happening again by validating that end_date > start_date.

Closing.
