### ISSUE TITLE
feat(common/FancyTable): auto-hide columns

### ISSUE THREAD

**Issue by QiLinXue** [volunteeringpeel/volunteeringpeel#77]
When the attendance page is first opened up, it is very clogged up. Although it is possible to manually hide columns, it is often repetitive as the same panels are hidden each time. It would be helpful if `Email` `Start and End` `Hours` `Other Shifts` and `Actions` are hidden by default.

**Comment by RetroCraft** [comment]
Considering that the table is based on the [`FancyTable`](https://github.com/volunteeringpeel/volunteeringpeel/blob/master/src/app/common/components/FancyTable.tsx) class, probably just gonna generalize and add a `props.headerRow[].hidden` or something.
