### ISSUE TITLE
After Daylight saving shift times back on save

### ISSUE THREAD

**Issue by QiLinXue** [volunteeringpeel/volunteeringpeel#97]
Steps to reproduce
* Create a new event and fill out all necessary boxes
* Change the date to after Nov 4th
* Set two random times
* Save
* Go back to event, and the time should be shifted back one hour
* Save again
* Go back to event, and time should be shifted back one hour again

**Comment by RetroCraft** [comment]
Going to test some stuff out with `moment-timezone`, but this might not get fixed until after the DST change considering that I just saw it and there's the Waterloo open house tomorrow.
